### ISSUE TITLE
Two factor authentication using docker

### ISSUE THREAD

**Issue by awirthy** [Zebradil/Gimme-iPhotos#26]
I've got docker to create the container but now it is asking for two factor authentication input after it is already running. At this point I can't enter the input needed.
Any thoughts?

**Comment by Zebradil** [comment]
Which command line do you use?

Make sure you run container  interactively with tty. For example: `docker run -it ...`.

**Comment by awirthy** [comment]
I was running it using powershell on Windows, but now I've managed to get it working.
Thanks.
