### ISSUE TITLE
CRITICAL:root:download_photos()

### ISSUE THREAD

**Issue by K-tron** [Zebradil/Gimme-iPhotos#36]
As best I can tell, download_photos is not expecting 'group_by_year_month_zero_pad' but it is being passed and causing a crash.

Version: 1.1.1

> CRITICAL:root:download_photos() takes from 4 to 5 positional arguments but 6 were given
> Traceback (most recent call last):
>   File "/home/briancatron/.local/lib/python3.8/site-packages/gimme_iphotos/__init__.py", line 95, in main
>     DownloaderApp(vars(args)).run()
>   File "/home/briancatron/.local/lib/python3.8/site-packages/gimme_iphotos/downloader.py", line 110, in run
>     icloud_photos = self.download_photos(
> TypeError: download_photos() takes from 4 to 5 positional arguments but 6 were given

**Comment by Zebradil** [comment]
Sorry, I should've tested the PR I had merged before.
Now it should be fixed.

**Comment by Zebradil** [comment]
The fix is released in [1.1.2](https://github.com/Zebradil/Gimme-iPhotos/releases/tag/1.1.2).
