### ISSUE TITLE
Docker image exits immediately when asking for 2fa confirmation 

### ISSUE THREAD

**Issue by norseghost** [Zebradil/Gimme-iPhotos#43]
Hi,

I am unable to interact with the 2fa message in any way while running from docker (on unraid, if it matters)

`docker container start gimme-iPhotos` pushes the new device login prompt to my idevices well enough; but immediately exits the container. Adding `-a` Or `-i` To the docker start command makes no difference 

tried adding a app specific password; but I’m still getting the 2fa prompt from the container (not idevices) and immediate container exit…

(I may well be holding something wrong somewhere — not a docker wizard here)

**Comment by Zebradil** [comment]
Have you tried to run it with the following (from the readme):

```shell
$ docker run -it \
    -v <destination>:/somedir \
    -v ${PWD}/john.cfg:/app/john.cfg \
    zebradil/gimme-iphotos -c john.cfg
```

The most important part here is `-it`, which means `--interactive --tty`, instead of just `--interactive`.

**Comment by norseghost** [comment]
Ah! Will do!

**Comment by norseghost** [comment]
And we’re up and running!

am I right in understanding that the script doesn’t keep in sync, but should be run periodically?
