### ISSUE TITLE
CRITICAL:root:'albumNameEnc'

### ISSUE THREAD

**Issue by MrBenFTW** [Zebradil/Gimme-iPhotos#7]
Hello, here is what I ran.

System: Centos7
User: root
Command:
`gimme-iphotos -u xx@xx.com -n 30 -v --destination /mnt/store/Photos`

Output:
```
Enter iCloud password for xx@xx.com: 
Two-step authentication required. Your trusted devices are:
  0: SMS to ********xx
Which device would you like to use? [0]: 0
Please enter validation code: xx
Succeed
Downloading all photos into '/mnt/store/Photos' while skipping existing…
CRITICAL:root:'albumNameEnc'
```

**Comment by MrBenFTW** [comment]
My server has a 10Gbps connection up/down so I assume -n 30 will utilise it well enough? Or what number should I set it to?

**Comment by Zebradil** [comment]
Please, try the latest version (1.0.6, I've just published it). It should print full stack trace on unhandled exceptions. So far I'm not sure I understand the essence of the issue.

The best number of parallel downloads depends in several factors and it's hard to say something without any tests. I guess the bottleneck with 10Gbps connection is apple's servers. So, just try different numbers and see how it goes. Please, share your results afterwards!

**Comment by MrBenFTW** [comment]
Hi, same issue. `CRITICAL:root:'albumNameEnc'`

It is also the same issue I posted here: [link](https://github.com/ndbroadbent/icloud_photos_downloader/issues/150)

**Comment by Zebradil** [comment]
It's a bug in the api library ([pyicloud](https://github.com/picklepete/pyicloud)).

Here is possible solution from the [issue](https://github.com/ndbroadbent/icloud_photos_downloader/issues/150) linked above:

> Turns out I had a weird ‘Untitled’/null album with no name and no photos in it.  I deleted that and everything seems to be running now.

_Originally posted by @pensphreak in https://github.com/ndbroadbent/icloud_photos_downloader/issues/150#issuecomment-652031627_
