### ISSUE TITLE
CRITICAL:root:list index out of range

### ISSUE THREAD

**Issue by moneyspider813** [Zebradil/Gimme-iPhotos#9]
Hello,

Running into an issue;

docker run -it -v C:\Users\daj81\Pictures\iCloudPhotos2020:/somedir -v C:\gimmeiphotos\david.cfg:/app/david.cfg zebradil/gimme-iphotos -c david.cfg -vvvv
DEBUG:app:Configuration: {'username': 'dajohnson92@icloud.com', 'password': '******', 'destination': '/somedir', 'overwrite': False, 'remove': 'False', 'parallel': 3}
INFO:app:Connecting to iCloud…
Two-step authentication required. Your trusted devices are:
  0: SMS to ********42
Which device would you like to use? [0]: 002186
CRITICAL:root:list index out of range
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/gimme_iphotos/__init__.py", line 79, in main
    DownloaderApp(vars(args)).run()
  File "/usr/local/lib/python3.8/site-packages/gimme_iphotos/downloader.py", line 106, in run
    api = self.connect_to_icloud(config)
  File "/usr/local/lib/python3.8/site-packages/gimme_iphotos/downloader.py", line 140, in connect_to_icloud
    device = devices[device]
IndexError: list index out of range

Thank you.

**Comment by Zebradil** [comment]
Take a look at this part:
```
Two-step authentication required. Your trusted devices are:
0: SMS to ********42
Which device would you like to use? [0]: 002186
```
Instead of `002186` (which is, I assume, a security code), you should have entered `0` — the number of the only device you have to send confirmation SMS to.

It'd be logical to avoid asking user to choose device if there is only one, but this is something I can't change as it comes from the underlying library.

**Comment by moneyspider813** [comment]
Thank you!!!!!!
